version: '3.7'
services:
  oracle-11g:
    image: gvenzl/oracle-xe:11-full
    restart: 'unless-stopped'
    container_name: oracle-11-xe
    environment:
      ORACLE_PASSWORD: oracle
      APP_USER: faouzi
      APP_USER_PASSWORD: faouzi

    ports:
      - 1521:1521
      
    networks:
      - ora11xe-net
      
    volumes:
      - ora11xe-v:/u01/app/oracle/oradata
      
  # apex-ords:
  #   image: container-registry.oracle.com/database/ords
  #   restart: 'unless-stopped'
  #   container_name: apex-ords
  #   depends_on:
  #     - oracle-11g

  #   ports:
  #     - 8181:8181
  #   volumes:
  #     - ~/APEX:/opt/oracle/variables
  #   networks:
  #     - ora11xe-net
  
volumes:
  ora11xe-v:

networks:
  ora11xe-net:
