version: '3.7'

services:
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    environment:
      - PGADMIN_DEFAULT_EMAIL=postgres@email.pg
      - PGADMIN_DEFAULT_PASSWORD=admin
      - PGADMIN_LISTEN_PORT=5000
      - PGADMIN_CONFIG_ENHANCED_COOKIE_PROTECTION=True
    ports:
      - "5000:5000"
    volumes:
      - pgad-volume:/var/lib/pgadmin
volumes:
  pgad-volume:

